version: '2.1'
services:
  postgresql:
    image: orchardup/postgresql:latest
    environment:
      - POSTGRESQL_USER=${POSTGRESQL_USER-sonar}
      - POSTGRESQL_PASS=${POSTGRESQL_PASS-xaexohquaetiesoo}
      - POSTGRESQL_DB=${POSTGRESQL_DB-sonar}
    volumes:
      - ${DATA_ROOT-.}/data/sonarqube/:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
  sonarqube:
    restart: always
    build:
      context: ./sonarqube/
      dockerfile: Dockerfile
    links:
      - postgresql:db
    environment:
      - SONARQUBE_JDBC_USERNAME=${POSTGRESQL_USER-sonar}
      - SONARQUBE_JDBC_PASSWORD=${POSTGRESQL_PASS-xaexohquaetiesoo}
      - SONARQUBE_JDBC_URL=${JDBC_URL-jdbc:postgresql://db/sonar}
    ports:
      - "9000:9000"
      - "443"
    depends_on:
      postgresql:
        condition: service_healthy